#ifndef SHADOWS_CONFIG_H
#define SHADOWS_CONFIG_H

//#define SHADOWS_UPVECTOR Y

#define SHADOWS_MAX_SPLITS 4

#define SHADOWS_DEBUG_ENABLED

#define SHADOWS_ENABLE_DX9_SUPPORT
//#define SHADOWS_ENABLE_DX10_SUPPORT

#endif // SHADOWS_CONFIG_H