name  := baseappmgr
type  := unit_test

include $(BW_COMPONENT_HEADER)

cxxSource =							\
			main					\

dependsOn += cstdmf

include $(BW_COMPONENT_FOOTER)

# vi: filetype=make
# Makefile.rules - baseappmgr/unit_test
