name  := res_packer
type  := binary
bindir = $(BW_SERVER_TOOLS_BIN_DIR)

include $(BW_COMPONENT_HEADER)

cxxSource =				\
	cdata_packer		\
	chunk_packer		\
	fx_packer			\
	image_packer		\
	main				\
	model_anim_packer	\
	msg_handler			\
	packer_helper		\
	packers				\
	xml_packer			\

buildTimeFile := main

dependsOn =		\
	chunk		\
	scene		\
	entitydef	\
	pyscript

usePython = 1

include $(BW_COMPONENT_FOOTER)

# vi: filetype=make
# Makefile.rules - res_packer
