name  := terrain
type  := unit_test

include $(BW_COMPONENT_HEADER)

cxxSource =							\
	main							\
	test_resource					\

# Currently Windows only
#	test_vertex_lod_manager			\

dependsOn += terrain cstdmf

include $(BW_COMPONENT_FOOTER)

# vi: filetype=make
# Makefile.rules - terrain/unit_test
