name         := waypoint
type         := library

include $(BW_COMPONENT_HEADER)


cxxSource =							\
	chunk_navigator					\
	chunk_waypoint					\
	chunk_waypoint_set				\
	chunk_waypoint_set_data 		\
	chunk_waypoint_set_state_path	\
	chunk_waypoint_set_state 		\
	chunk_waypoint_state 			\
	chunk_waypoint_state_path		\
	girth_grid_list					\
	navigator						\
	navigator_cache					\
	navloc							\
	waypoint_neighbour_iterator		\
	waypoint_stats					\


usePython = 1


include $(BW_COMPONENT_FOOTER)

# vi: filetype=make
# Makefile.rules - libwaypoint
