#ifndef DEBUG_MESSAGE_CATEGORY_HPP
#define DEBUG_MESSAGE_CATEGORY_HPP

// ---- Billing category ----

#define BILLING_TRACE_MSG TRACE_MSG_WITH_CATEGORY( Billing )
#define BILLING_DEBUG_MSG DEBUG_MSG_WITH_CATEGORY( Billing )
#define BILLING_INFO_MSG INFO_MSG_WITH_CATEGORY( Billing )
#define BILLING_NOTICE_MSG NOTICE_MSG_WITH_CATEGORY( Billing )
#define BILLING_WARNING_MSG WARNING_MSG_WITH_CATEGORY( Billing )
#define BILLING_ERROR_MSG ERROR_MSG_WITH_CATEGORY( Billing )
#define BILLING_CRITICAL_MSG CRITICAL_MSG_WITH_CATEGORY( Billing )
#define BILLING_HACK_MSG HACK_MSG_WITH_CATEGORY( Billing )
#define BILLING_ASSET_MSG ASSET_MSG_WITH_CATEGORY( Billing )


// ---- Chunk category ----

#define CHUNK_TRACE_MSG TRACE_MSG_WITH_CATEGORY( Chunk )
#define CHUNK_DEBUG_MSG DEBUG_MSG_WITH_CATEGORY( Chunk )
#define CHUNK_INFO_MSG INFO_MSG_WITH_CATEGORY( Chunk )
#define CHUNK_NOTICE_MSG NOTICE_MSG_WITH_CATEGORY( Chunk )
#define CHUNK_WARNING_MSG WARNING_MSG_WITH_CATEGORY( Chunk )
#define CHUNK_ERROR_MSG ERROR_MSG_WITH_CATEGORY( Chunk )
#define CHUNK_CRITICAL_MSG CRITICAL_MSG_WITH_CATEGORY( Chunk )
#define CHUNK_HACK_MSG HACK_MSG_WITH_CATEGORY( Chunk )
#define CHUNK_ASSET_MSG ASSET_MSG_WITH_CATEGORY( Chunk )

// ---- Config category ----

#define CONFIG_TRACE_MSG TRACE_MSG_WITH_CATEGORY( Config )
#define CONFIG_DEBUG_MSG DEBUG_MSG_WITH_CATEGORY( Config )
#define CONFIG_INFO_MSG INFO_MSG_WITH_CATEGORY( Config )
#define CONFIG_NOTICE_MSG NOTICE_MSG_WITH_CATEGORY( Config )
#define CONFIG_WARNING_MSG WARNING_MSG_WITH_CATEGORY( Config )
#define CONFIG_ERROR_MSG ERROR_MSG_WITH_CATEGORY( Config )
#define CONFIG_CRITICAL_MSG CRITICAL_MSG_WITH_CATEGORY( Config )
#define CONFIG_HACK_MSG HACK_MSG_WITH_CATEGORY( Config )
#define CONFIG_ASSET_MSG ASSET_MSG_WITH_CATEGORY( Config )


// ---- DBEngine category ----

#define DBENGINE_TRACE_MSG TRACE_MSG_WITH_CATEGORY( DBEngine )
#define DBENGINE_DEBUG_MSG DEBUG_MSG_WITH_CATEGORY( DBEngine )
#define DBENGINE_INFO_MSG INFO_MSG_WITH_CATEGORY( DBEngine )
#define DBENGINE_NOTICE_MSG NOTICE_MSG_WITH_CATEGORY( DBEngine )
#define DBENGINE_WARNING_MSG WARNING_MSG_WITH_CATEGORY( DBEngine )
#define DBENGINE_ERROR_MSG ERROR_MSG_WITH_CATEGORY( DBEngine )
#define DBENGINE_CRITICAL_MSG CRITICAL_MSG_WITH_CATEGORY( DBEngine )
#define DBENGINE_HACK_MSG HACK_MSG_WITH_CATEGORY( DBEngine )
#define DBENGINE_ASSET_MSG ASSET_MSG_WITH_CATEGORY( DBEngine )


// ---- Network category ----

#define NETWORK_TRACE_MSG TRACE_MSG_WITH_CATEGORY( Network )
#define NETWORK_DEBUG_MSG DEBUG_MSG_WITH_CATEGORY( Network )
#define NETWORK_INFO_MSG INFO_MSG_WITH_CATEGORY( Network )
#define NETWORK_NOTICE_MSG NOTICE_MSG_WITH_CATEGORY( Network )
#define NETWORK_WARNING_MSG WARNING_MSG_WITH_CATEGORY( Network )
#define NETWORK_ERROR_MSG ERROR_MSG_WITH_CATEGORY( Network )
#define NETWORK_CRITICAL_MSG CRITICAL_MSG_WITH_CATEGORY( Network )
#define NETWORK_HACK_MSG HACK_MSG_WITH_CATEGORY( Network )
#define NETWORK_ASSET_MSG ASSET_MSG_WITH_CATEGORY( Network )


// ---- Process IP category ----

#define PROC_IP_TRACE_MSG TRACE_MSG_WITH_CATEGORY( ProcessIP )
#define PROC_IP_DEBUG_MSG DEBUG_MSG_WITH_CATEGORY( ProcessIP )
#define PROC_IP_INFO_MSG INFO_MSG_WITH_CATEGORY( ProcessIP )
#define PROC_IP_NOTICE_MSG NOTICE_MSG_WITH_CATEGORY( ProcessIP )
#define PROC_IP_WARNING_MSG WARNING_MSG_WITH_CATEGORY( ProcessIP )
#define PROC_IP_ERROR_MSG ERROR_MSG_WITH_CATEGORY( ProcessIP )
#define PROC_IP_CRITICAL_MSG CRITICAL_MSG_WITH_CATEGORY( ProcessIP )
#define PROC_IP_HACK_MSG HACK_MSG_WITH_CATEGORY( ProcessIP )
#define PROC_IP_ASSET_MSG ASSET_MSG_WITH_CATEGORY( ProcessIP )

// ---- Script category ----

#define SCRIPT_TRACE_MSG TRACE_MSG_WITH_CATEGORY( Script )
#define SCRIPT_DEBUG_MSG DEBUG_MSG_WITH_CATEGORY( Script )
#define SCRIPT_INFO_MSG INFO_MSG_WITH_CATEGORY( Script )
#define SCRIPT_NOTICE_MSG NOTICE_MSG_WITH_CATEGORY( Script )
#define SCRIPT_WARNING_MSG WARNING_MSG_WITH_CATEGORY( Script )
#define SCRIPT_ERROR_MSG ERROR_MSG_WITH_CATEGORY( Script )
#define SCRIPT_CRITICAL_MSG CRITICAL_MSG_WITH_CATEGORY( Script )
#define SCRIPT_HACK_MSG HACK_MSG_WITH_CATEGORY( Script )
#define SCRIPT_ASSET_MSG ASSET_MSG_WITH_CATEGORY( Script )

// ---- SecondaryDB category ----

#define SECONDARYDB_TRACE_MSG TRACE_MSG_WITH_CATEGORY( SecondaryDB )
#define SECONDARYDB_DEBUG_MSG DEBUG_MSG_WITH_CATEGORY( SecondaryDB )
#define SECONDARYDB_INFO_MSG INFO_MSG_WITH_CATEGORY( SecondaryDB )
#define SECONDARYDB_NOTICE_MSG NOTICE_MSG_WITH_CATEGORY( SecondaryDB )
#define SECONDARYDB_WARNING_MSG WARNING_MSG_WITH_CATEGORY( SecondaryDB )
#define SECONDARYDB_ERROR_MSG ERROR_MSG_WITH_CATEGORY( SecondaryDB )
#define SECONDARYDB_CRITICAL_MSG CRITICAL_MSG_WITH_CATEGORY( SecondaryDB )
#define SECONDARYDB_HACK_MSG HACK_MSG_WITH_CATEGORY( SecondaryDB )
#define SECONDARYDB_ASSET_MSG ASSET_MSG_WITH_CATEGORY( SecondaryDB )


// ---- Response category ----

#define RESPONSE_TRACE_MSG TRACE_MSG_WITH_CATEGORY( Response )
#define RESPONSE_DEBUG_MSG DEBUG_MSG_WITH_CATEGORY( Response )
#define RESPONSE_INFO_MSG INFO_MSG_WITH_CATEGORY( Response )
#define RESPONSE_NOTICE_MSG NOTICE_MSG_WITH_CATEGORY( Response )
#define RESPONSE_WARNING_MSG WARNING_MSG_WITH_CATEGORY( Response )
#define RESPONSE_ERROR_MSG ERROR_MSG_WITH_CATEGORY( Response )
#define RESPONSE_CRITICAL_MSG CRITICAL_MSG_WITH_CATEGORY( Response )
#define RESPONSE_HACK_MSG HACK_MSG_WITH_CATEGORY( Response )
#define RESPONSE_ASSET_MSG ASSET_MSG_WITH_CATEGORY( Response )

#endif // DEBUG_MESSAGE_CATEGORY_HPP
