BIN = dbapp_indie

BUILD_TIME_FILE = main_indie

SRCS = main_indie

BILLING_SYSTEM_SRCS = bwauth_billing_system

MY_LIBS += urlrequest

USE_LIBJSON=1
USE_LIBCURL=1

ifndef MF_ROOT
export MF_ROOT := $(subst /bigworld/src/server/dbapp,,$(CURDIR))
endif

include $(MF_ROOT)/bigworld/src/server/dbapp/Makefile.common
