name         := urlrequest
type         := library

include $(BW_COMPONENT_HEADER)

cxxSource =		\
	manager		\
	request		\
	response	\
	string_list	\


useCurl = 1

include $(BW_COMPONENT_FOOTER)

# vi: filetype=make
# Makefile.rules - liburlrequest
