$(call includeUnitTestDirectory)

name  := reviver
type  := binary
bindir = $(BW_SERVER_BIN_DIR)

include $(BW_COMPONENT_HEADER)

cxxSource =									\
	main									\
	component_reviver						\
	reviver									\
	reviver_config							\
	../baseappmgr/baseappmgr_interface		\
	../cellappmgr/cellappmgr_interface		\


buildTimeFile := main

dependsOn  = 	\
	db 			\
	server

incFlags_$(binName) += -I$(BW_ABS_SRC_SERVER)

include $(BW_COMPONENT_FOOTER)

# vi: filetype=make
# Makefile.rules - reviver
