.DEFAULT_GOAL = bw-libraries

include ../Makefile

# TODO: potentially re-implement
# unit_tests: unit_tests_build unit_tests_run
# unit_tests_build:
# unit_tests_run:
# unit_tests_clean:

# Makefile - src/lib
